name: Feature Request
description: Suggest an idea for Motodriver library.
title: "[Feature Request]"
labels: [enhancement]
assignees:
  - Arxaid
body:
  - type: checkboxes
    id: check
    attributes:
      label: "Did you search other suggestions?"
      options:
      - label: "I have checked if this feature request exists already"
        required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please write a clear and concise description of what the problem is."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Screenshots and / or description of the feature request"
      description: "Please write a detailed description about how the feature will work, and be implemented, optionally providing screenshots."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: "Why does Motodriver library need this?"
      description: "A detailed description of why this could benefit either the management team, the users, or both."
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here, or leave blank."